version: '2'
services:
  cabin_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: idrive
      MYSQL_DATABASE: econet
      MYSQL_USER: idrive
      MYSQL_PASSWORD: idrive#2018
